PAYLAPMEXT-295: mise a jour des nouveau code erreurs
PaylinePaymentMethod/payment-method-ppewshop pull request #2
Opened 2020-10-26 10:18 UTC by JanFLORENT

+ corrections codeSmells Sonar
+ correction Gradle

![image](https://user-images.githubusercontent.com/41673610/97160627-ec228180-177c-11eb-8e01-00fd7cd2fd6e.png)

les configurations n'ont pas changé

2020-11-16 14:20 UTC, pesublet requested changes

2020-11-16 14:20 UTC, pesublet commented on src/main/java/com/payline/payment/ppewshop/utils/GoodsCodeBusiness.java
> +    public static String getGoodsCode(String cat) {
Il faudrait plutôt favoriser un service plus qu'une méthodes static, toujours compliquée à mocker. reprendre par ex : private GenericPaymentService genericPaymentService = GenericPaymentService.getInstance();

2020-11-23 10:13 UTC, JanFLORENT commented on src/main/java/com/payline/payment/ppewshop/utils/GoodsCodeBusiness.java
> +    public static String getGoodsCode(String cat) {
fait

2020-11-23 10:28 UTC, JanFLORENT commented
![image](https://user-images.githubusercontent.com/41673610/99951819-f9805b00-2d7e-11eb-81bb-f5b372e9fc06.png)

2020-11-24 14:19 UTC, pesublet approved these changes

2020-11-24 14:19 UTC, merged