PAYLAPMEXT-298: inversion des URLs de redirection & notification
PaylinePaymentMethod/payment-method-ppewshop pull request #4
Opened 2020-11-03 10:16 UTC by JanFLORENT

Les configs ne changent pas.
![image](https://user-images.githubusercontent.com/41673610/97973125-e6085280-1dc5-11eb-8861-7126b1346da1.png)

certains codesmells sont corrigé dans la livraison du ticket 295

2020-11-16 14:17 UTC, pesublet requested changes

2020-11-16 14:17 UTC, pesublet commented on src/main/java/com/payline/payment/ppewshop/service/impl/PaymentServiceImpl.java
> -                .withGuardBackUrl(request.getEnvironment().getNotificationURL())
Je veux bien un TU sur le changement effectué :)

2020-11-23 14:52 UTC, JanFLORENT commented on src/main/java/com/payline/payment/ppewshop/service/impl/PaymentServiceImpl.java
> -                .withGuardBackUrl(request.getEnvironment().getNotificationURL())
fait

2020-11-24 10:41 UTC, pesublet approved these changes
impec, merci !

2020-11-24 10:42 UTC, merged